spring.cloud.stream:
  function.definition: supplier;receive1;receive2;
  bindings:
    receive1-in-0.destination: customerId-1
    receive2-in-0.destination: customerId-2


solace:
  java:
    host: localhost
    msgVpn: default
    clientUsername: default
    clientPassword: default
    connectRetries: -1
    reconnectRetries: -1

