spring:
  cloud:
    function:
      definition: emitSensorReading
    stream:
      poller:
        fixed-delay: 5000
      bindings:
        emitSensorReading-out-0:
          destination: sensor/temperature/fahrenheit
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://20.79.227.77:55555
                msgVpn: lidl-staging
                clientUsername: lidl-staging
                clientPassword: jdn41!SDF5
                connectRetries: -1
                reconnectRetries: -1
logging:
  level:
    root: INFO
    com.solacesystems.jcsmp: INFO
    org.springframework: INFO