Spring Cloud Stream Sink Sample
================================

This sample is one of the original Spring Cloud Stream samples that was hand-picked to demonstrate the link:https://github.com/SolaceProducts/spring-cloud-stream-binder-solace[Solace Spring Cloud Stream Binder]. The original source for this sample can be found link:https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/sink-samples/jdbc-sink[here].

## What is this app?

This is a Spring Boot application that is a Spring Cloud Stream sample sink app that inserts data into a database through JDBC.
This application specifically uses MySQL (MariaDB flavor) to insert the data.
In reality, you probably want to use the out of the box variant of JDBC sink from https://github.com/spring-cloud-stream-app-starters/jdbc which is more advanced.
Refer to the documentation of Spring Cloud Stream app starters for the latest links for generated apps for specific binders.

## Requirements

To run this sample, you will need to have installed:

* Java 8 or Above

## Running the application


The following instructions assume that:

* You are running a local MySql (MariaDB) service
* Have a database called `sample_mysql_db`
* Have the credentials for a real Solace PubSub+ service

Now to run the application:

* Open another terminal and go to the application root (root of this sample app `sink`)
* Put your database credentials in the link:src/main/resources/application.yml[application.yml] file
* Put your Solace credentials in the link:src/main/resources/application.yml[application.yml] file
* `./mvnw clean package`
* `java -jar target/jdbc-sink-0.0.1-SNAPSHOT.jar`

When you start the app, it will create a table in the database.
See the method annotated with`PostConstruct` in the application for more details.

The application has a convenient test source that sends to the same destination on the broker where the sink consumes data from.
This test source will send some test records every second.

Now go to see the test table being populated in the MySQL CLI:

* Ensure that you have the `mysql` CLI tool installed and then use this command:
`mysql -u root -p  -h 127.0.0.1 -P 3306 sample_mysql_db`
* `select * from test;`

Repeat the query a few times and you will see additional records each time.
